-- COC Extension Installation Helper
-- This ensures COC extensions are installed properly

-- local M = {}
--
-- local coc_extensions = {
--     'coc-json',
--     'coc-tsserver',
--     'coc-pyright',
--     'coc-rust-analyzer',
--     'coc-lua',
--     'coc-snippets'
-- }
--
-- function M.install_extensions()
--     -- Wait for COC to be fully loaded
--     local max_attempts = 10
--     local attempt = 0
--
--     local function try_install()
--         attempt = attempt + 1
--
--         -- Check if COC is available
--         if vim.fn.exists(':CocInstall') ~= 2 then
--             if attempt < max_attempts then
--                 vim.defer_fn(try_install, 1000) -- Try again in 1 second
--                 return
--             else
--                 vim.notify("COC not available for extension installation", vim.log.levels.WARN)
--                 return
--             end
--         end
--
--         -- Check which extensions are missing
--         local missing_extensions = {}
--         for _, ext in ipairs(coc_extensions) do
--             local ext_path = vim.fn.expand('~/.config/coc/extensions/node_modules/' .. ext)
--             if vim.fn.isdirectory(ext_path) == 0 then
--                 table.insert(missing_extensions, ext)
--             end
--         end
--
--         -- Install missing extensions
--         if #missing_extensions > 0 then
--             vim.notify("Installing COC extensions: " .. table.concat(missing_extensions, ', '), vim.log.levels.INFO)
--             vim.cmd('silent! wall')
--
--             -- Use a more reliable installation method
--             local install_cmd = 'CocInstall -sync ' .. table.concat(missing_extensions, ' ')
--             local success = pcall(vim.cmd, install_cmd)
--
--             if success then
--                 vim.notify("COC extensions installed successfully", vim.log.levels.INFO)
--             else
--                 vim.notify("Failed to install COC extensions. Try running :CocInstall manually", vim.log.levels.ERROR)
--             end
--         else
--             vim.notify("All COC extensions are already installed", vim.log.levels.INFO)
--         end
--     end
--
--     -- Start the installation process
--     vim.defer_fn(try_install, 2000) -- Wait 2 seconds for COC to load
-- end
--
-- -- Manual installation command
-- function M.install_missing()
--     M.install_extensions()
-- end
--
-- -- Check extension status
-- function M.check_status()
--     local installed = {}
--     local missing = {}
--
--     for _, ext in ipairs(coc_extensions) do
--         local ext_path = vim.fn.expand('~/.config/coc/extensions/node_modules/' .. ext)
--         if vim.fn.isdirectory(ext_path) == 1 then
--             table.insert(installed, ext)
--         else
--             table.insert(missing, ext)
--         end
--     end
--
--     print("COC Extensions Status:")
--     print("Installed: " .. (#installed > 0 and table.concat(installed, ', ') or 'None'))
--     print("Missing: " .. (#missing > 0 and table.concat(missing, ', ') or 'None'))
--
--     return #missing == 0
-- end
--
-- return M

